# Generated by Django 5.0.4 on 2024-10-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expense_category',
            field=models.CharField(blank=True, choices=[('bills', 'Bills'), ('savings', 'Savings'), ('debts', 'Debts')], max_length=7, null=True),
        ),
    ]
