# Generated by Django 5.0.4 on 2024-10-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transaction_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expense_category',
            field=models.CharField(blank=True, choices=[('bills', 'Bills'), ('savings', 'Savings'), ('debts', 'Debts'), ('others', 'Others')], max_length=7, null=True),
        ),
    ]
